"https://www.{default}/":
    type: upstream
    upstream: "gatsby:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://www.backend.{default}/":
    type: upstream
    upstream: "strapi:http"

"https://backend.{default}/":
    type: redirect
    id: 'strapi'
    to: "https://www.backend.{default}/"